import fs from 'node:fs';

// entry id -> unix timestamp, generated by scripts/gen-dates.mjs (git blame).
// Empty when built without git history.
let dates: Record<string, number> = {};
try {
  dates = JSON.parse(fs.readFileSync('dates.json', 'utf8'));
} catch {
  /* dates.json missing */
}

export const addedDates = dates;
